name: Go Build

on:
  push:
    branches:
      - main  # Esegui il workflow su ogni push alla branch main
  pull_request:
    branches:
      - main  # Esegui il workflow su ogni pull request verso la branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'  # Specifica la versione di Go che vuoi utilizzare

    - name: Build server
      run: |
        go build -o bin/server ./main/server

    - name: Build client
      run: go build -o bin/client ./main/client
